import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import ReactQueryClientProvider from '@/providers/ReactQueryClientProvider';
import { cn } from '@/lib/utils';
import './globals.css';

const fontSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['300', '400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn('antialiased bg-primary-background', fontSans.variable)}>
        <ReactQueryClientProvider>
          <main className="p-6 mx-auto max-w-7xl">{children}</main>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
